# Generated by Django 5.0.2 on 2024-04-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_group_hashtag_multichoicequestion_questionchoicedata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
    ]
