# Generated by Django 5.0.2 on 2024-04-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_rename_department_course_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='department',
        ),
    ]
