# Generated by Django 5.0.4 on 2024-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0010_alter_answers_question_alter_replies_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
