# Generated by Django 5.0.4 on 2024-04-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0011_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alpha.news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('premium', 'Premium'), ('freemium', 'Freemium')], default='freemium', max_length=20),
        ),
    ]
