# Generated by Django 5.0.4 on 2024-04-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0013_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
