# Generated by Django 5.0.4 on 2024-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0014_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
