# Generated by Django 5.0.4 on 2024-05-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0016_savedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_saved',
        ),
    ]
