# Generated by Django 5.0.4 on 2024-05-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0017_remove_questions_is_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='liked',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='number_of_likes',
        ),
    ]
