# Generated by Django 5.0.4 on 2024-05-03 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0019_likedanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='is_saved',
        ),
        migrations.AddField(
            model_name='answers',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebook',
            name='file',
            field=models.FileField(default='', upload_to='ebook_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_type',
            field=models.CharField(choices=[('.docx', '.docx'), ('.pdf', '.pdf'), ('.epub', '.epub')], default='.pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover_image',
            field=models.ImageField(upload_to='ebook_cover'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SavedEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LikedAnswers',
        ),
    ]
