# Generated by Django 5.0.4 on 2024-05-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0020_remove_ebook_is_saved_answers_likes_ebook_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_saved',
        ),
    ]
