# Generated by Django 5.0.4 on 2024-05-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0021_remove_quiz_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='explanation',
        ),
        migrations.AddField(
            model_name='questionexplanation',
            name='question',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='alpha.multichoicequestion'),
            preserve_default=False,
        ),
    ]
