# Generated by Django 5.0.4 on 2024-05-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0022_remove_multichoicequestion_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='comment',
        ),
        migrations.AddField(
            model_name='questioncomments',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alpha.multichoicequestion'),
        ),
    ]
