# Generated by Django 5.0.4 on 2024-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0024_paymentmethod_pricing_submitpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='savedebooks',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='questioncomments',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionexplanation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='questioncomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='department',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedebooks',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ebook',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MultiChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionExplanation',
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
        migrations.DeleteModel(
            name='QuestionChoiceData',
        ),
        migrations.DeleteModel(
            name='QuestionComments',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='SavedEbooks',
        ),
    ]
