# Generated by Django 5.0.4 on 2024-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0025_paymentswitch_remove_savedebooks_ebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('premium', 'Premium'), ('pending', 'Pending'), ('freemium', 'Freemium')], default='freemium', max_length=20),
        ),
    ]
